use std::fs::File;
use std::io::{Read, Write};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use std::thread;
use std::time::Duration;
#[cfg(target_os = "windows")]
use std::os::windows::process::CommandExt;

/// Prevents a console window from flashing when spawning PowerShell subprocesses.
#[cfg(target_os = "windows")]
const CREATE_NO_WINDOW: u32 = 0x08000000;

use tauri::{
    AppHandle, Manager, Runtime,
    tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent},
    menu::{Menu, MenuEvent, MenuItem},
    window::Color,
};
use tauri_plugin_autostart::MacosLauncher;
use tauri_plugin_opener::OpenerExt;
use tauri_plugin_shell::ShellExt;
use tauri_plugin_shell::process::CommandEvent;
use serde::Deserialize;
use tauri::menu::PredefinedMenuItem;

// Prevents two concurrent update flows (startup check + manual "Check for Updates" click).
static UPDATE_IN_PROGRESS: AtomicBool = AtomicBool::new(false);
// Latest available version tag found by background check, shown non-intrusively in the UI.
static AVAILABLE_UPDATE: Mutex<Option<String>> = Mutex::new(None);
// Set to true once a manual update check triggered by the user completes (either found or not found).
// Lets the renderer stop polling immediately instead of waiting the full 20s timeout.
static UPDATE_CHECK_DONE: AtomicBool = AtomicBool::new(false);
// Last error from a user-initiated update check, shown in the Settings UI.
static UPDATE_CHECK_ERROR: Mutex<Option<String>> = Mutex::new(None);
// Download progress string shown in the agent UI, e.g. "45 / 83 MB (54%)". None when idle.
static DOWNLOAD_PROGRESS: Mutex<Option<String>> = Mutex::new(None);
// Ephemeral shared secret generated by the sidecar on each startup.
// Captured from sidecar stdout by the watchdog and required on every HTTP request
// to the sidecar (except OPTIONS preflights and the /health endpoint).
static SIDECAR_TOKEN: Mutex<Option<String>> = Mutex::new(None);

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/// Called from the setup window renderer when the user submits the config form.
/// apiKey is empty-string when the user wants to keep the previously saved key.
#[tauri::command]
fn save_config(
    _app: AppHandle,
    api_key: String,
    server_url: String,
) -> Result<(), String> {
    // Build body — omit apiKey entirely when empty so the sidecar reuses its
    // saved key (avoids forcing the user to re-enter it every time).
    let body = if api_key.is_empty() {
        serde_json::json!({ "serverUrl": server_url })
    } else {
        serde_json::json!({ "apiKey": api_key, "serverUrl": server_url })
    };

    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(3))
        .build()
        .map_err(|e| e.to_string())?;

    // Retry up to 3 times — sidecar may still be starting.
    let mut last_err = String::new();
    for attempt in 0..3u8 {
        if attempt > 0 {
            thread::sleep(Duration::from_secs(1));
        }
        match with_token(client.post("http://127.0.0.1:9001/config").json(&body)).send() {
            Ok(resp) => {
                resp.error_for_status()
                    .map_err(|e| format!("Sidecar returned error: {e}"))?;
                // Window stays open — the renderer shows a success banner and
                // the user can switch to the Logs tab or close manually.
                return Ok(());
            }
            Err(e) => last_err = e.to_string(),
        }
    }

    Err(format!(
        "Could not reach the agent sidecar on port 9001 after 3 attempts.\n\
         Make sure the sidecar is running (in dev mode: cd scraper-node && npm run dev).\n\n\
         Detail: {last_err}"
    ))
}

/// Returns the latest available version tag found by the background update check,
/// or null if no update is available. Called from the renderer to show the update badge.
#[tauri::command]
fn get_update_version() -> Option<String> {
    AVAILABLE_UPDATE.lock().ok().and_then(|g| g.clone())
}

/// Returns the current sidecar shared secret so the renderer can include it in
/// every fetch request as `X-Sidecar-Token`. Returns None only during the brief
/// window between sidecar crash and watchdog restart — renderer retries on null.
#[tauri::command]
fn get_sidecar_token() -> Option<String> {
    SIDECAR_TOKEN.lock().ok().and_then(|g| g.clone())
}

#[tauri::command]
fn window_minimize(window: tauri::WebviewWindow) -> Result<(), String> {
    window.minimize().map_err(|e| e.to_string())
}

#[tauri::command]
fn window_toggle_maximize(window: tauri::WebviewWindow) -> Result<(), String> {
    if window.is_maximized().map_err(|e| e.to_string())? {
        window.unmaximize().map_err(|e| e.to_string())
    } else {
        window.maximize().map_err(|e| e.to_string())
    }
}

#[tauri::command]
fn window_close(window: tauri::WebviewWindow) -> Result<(), String> {
    window.close().map_err(|e| e.to_string())
}

#[tauri::command]
fn window_start_dragging(window: tauri::WebviewWindow) -> Result<(), String> {
    window.start_dragging().map_err(|e| e.to_string())
}

/// Triggers the download + install flow. Re-checks GitHub at click time to always
/// get the absolute latest release (not the cached badge version).
/// Called from the renderer when the user clicks the update badge.
#[tauri::command]
fn install_update(app: AppHandle) {
    // Guard against concurrent clicks — but reset before calling
    // handle_update_available so it can take ownership of the flag itself.
    if UPDATE_IN_PROGRESS.swap(true, Ordering::SeqCst) {
        return; // already in progress
    }
    UPDATE_IN_PROGRESS.store(false, Ordering::SeqCst);
    UPDATE_CHECK_DONE.store(false, Ordering::SeqCst);

    let current_version = app.package_info().version.to_string();
    thread::spawn(move || {
        sidecar_log_quick("info", "[agent] Update install initiated by user");
        match check_for_update(&current_version) {
            Ok(Some(latest_tag)) => {
                if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                    *guard = Some(latest_tag.clone());
                }
                if let Ok(mut guard) = UPDATE_CHECK_ERROR.lock() { *guard = None; }
                UPDATE_CHECK_DONE.store(true, Ordering::SeqCst);
                handle_update_available(&app, &latest_tag);
            }
            Ok(None) => {
                // Already on latest — clear badge and any previous error
                if let Ok(mut guard) = AVAILABLE_UPDATE.lock() { *guard = None; }
                if let Ok(mut guard) = UPDATE_CHECK_ERROR.lock() { *guard = None; }
                UPDATE_CHECK_DONE.store(true, Ordering::SeqCst);
                sidecar_log_quick("info", "[agent] Update check: already on latest version");
            }
            Err(e) => {
                if let Ok(mut guard) = UPDATE_CHECK_ERROR.lock() { *guard = Some(e.clone()); }
                UPDATE_CHECK_DONE.store(true, Ordering::SeqCst);
                sidecar_log_quick("error", &format!("[agent] Update check failed: {e}"));
            }
        }
    });
}

/// Returns true once the manual update check triggered by install_update has completed.
/// Lets the renderer stop polling immediately instead of waiting the full 20s timeout.
#[tauri::command]
fn is_update_check_done() -> bool {
    UPDATE_CHECK_DONE.load(Ordering::SeqCst)
}

/// Returns the error message from the last user-initiated update check, or null if no error.
#[tauri::command]
fn get_update_check_error() -> Option<String> {
    UPDATE_CHECK_ERROR.lock().ok().and_then(|g| g.clone())
}

/// Returns the current download progress string (e.g. "45 / 83 MB (54%)"),
/// or null when no download is in progress.
#[tauri::command]
fn get_download_progress() -> Option<String> {
    DOWNLOAD_PROGRESS.lock().ok().and_then(|g| g.clone())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Attach the current sidecar token as `X-Sidecar-Token` to a request builder.
/// Returns the builder unchanged when no token is stored (e.g. during restart).
fn with_token(req: reqwest::blocking::RequestBuilder) -> reqwest::blocking::RequestBuilder {
    match SIDECAR_TOKEN.lock().ok().and_then(|g| g.clone()) {
        Some(t) => req.header("X-Sidecar-Token", t),
        None => req,
    }
}

/// Wait up to ~10 s for the sidecar HTTP server to respond on :9001.
fn wait_for_sidecar() -> bool {
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()
        .unwrap();

    for _ in 0..10 {
        if client.get("http://127.0.0.1:9001/health").send().is_ok() {
            return true;
        }
        thread::sleep(Duration::from_secs(1));
    }
    false
}

#[derive(Deserialize)]
struct HealthResponse {
    #[serde(rename = "hasApiKey")]
    has_api_key: bool,
}

#[derive(Deserialize)]
struct ScheduleResponse {
    #[serde(rename = "nextRunAt")]
    next_run_at: Option<u64>, // epoch ms, null while running or not configured
}

#[derive(Deserialize)]
struct UpdateCheckResponse {
    pending: bool,
}

#[derive(Deserialize)]
struct GitHubRelease {
    tag_name: String,
}

/// Post a log message to the sidecar's /log endpoint so it appears in the agent UI.
fn sidecar_log(client: &reqwest::blocking::Client, level: &str, msg: &str) {
    let body = format!(r#"{{"level":"{}","msg":"{}"}}"#, level, msg.replace('"', "\\\""));
    let _ = with_token(
        client
            .post("http://127.0.0.1:9001/log")
            .header("Content-Type", "application/json")
            .body(body),
    )
    .send();
}

/// One-shot sidecar log — creates its own client, use when no client is available.
fn sidecar_log_quick(level: &str, msg: &str) {
    if let Ok(client) = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(3))
        .build()
    {
        sidecar_log(&client, level, msg);
    }
}

/// Check GitHub releases API for a newer version.
/// Returns Ok(Some(tag)) if an update is available, Ok(None) if already on latest,
/// or Err(description) if the API call failed (network error, auth, 404, etc.).
fn check_for_update(current_version: &str) -> Result<Option<String>, String> {
    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(10))
        .build()
        .map_err(|e| format!("Failed to build HTTP client: {e}"))?;

    let mut req = client
        .get("https://api.github.com/repos/Bishi/auto-scraper-agent/releases/latest")
        .header("User-Agent", "auto-scraper-agent");

    // Optional GitHub token — required when the repo is private.
    // Set GITHUB_TOKEN at build time (e.g. in the GitHub Actions release workflow).
    if let Some(token) = option_env!("GITHUB_TOKEN") {
        req = req.header("Authorization", format!("Bearer {token}"));
    }

    let response = req.send().map_err(|e| format!("Network error: {e}"))?;
    let status = response.status();
    if !status.is_success() {
        return Err(format!("GitHub API returned {status}"));
    }

    let release: GitHubRelease = response
        .json()
        .map_err(|e| format!("Failed to parse GitHub response: {e}"))?;

    let latest = release.tag_name.trim_start_matches('v');
    if latest != current_version {
        Ok(Some(release.tag_name))
    } else {
        Ok(None)
    }
}

// ---------------------------------------------------------------------------
// Update dialogs — PowerShell MessageBox (no extra dependencies, Windows-only)
// ---------------------------------------------------------------------------

/// DPI-awareness bootstrap prepended to every dialog script.
///
/// Each dialog runs in a fresh powershell.exe process which is not DPI-aware
/// by default, causing blurry rendering on high-DPI / scaled displays.
/// Calling SetProcessDPIAware() before showing any WinForms control fixes it.
const DPI_PREFIX: &str = concat!(
    "Add-Type -MemberDefinition '[DllImport(\"user32.dll\")] ",
    "public static extern bool SetProcessDPIAware();' ",
    "-Name DpiHelper -Namespace Win32 -PassThru | Out-Null; ",
    "[Win32.DpiHelper]::SetProcessDPIAware() | Out-Null; ",
    "[System.Reflection.Assembly]::LoadWithPartialName('System.Windows.Forms') | Out-Null; ",
);

/// Show a Yes/No dialog. Returns true if the user clicked Yes.
fn dialog_yes_no(title: &str, message: &str) -> bool {
    // Escape single quotes for PowerShell string literals
    let msg   = message.replace('\'', "''");
    let title = title.replace('\'', "''");
    let script = format!(
        "{DPI_PREFIX}[System.Windows.Forms.MessageBox]::Show('{msg}', '{title}', \
         'YesNo', 'Question') -eq 'Yes'"
    );
    std::process::Command::new("powershell")
        .args(["-WindowStyle", "Hidden", "-NonInteractive", "-Command", &script])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).trim() == "True")
        .unwrap_or(false)
}

/// Show an informational OK dialog.
fn dialog_ok(title: &str, message: &str) {
    let msg   = message.replace('\'', "''");
    let title = title.replace('\'', "''");
    let script = format!(
        "{DPI_PREFIX}[System.Windows.Forms.MessageBox]::Show('{msg}', '{title}', \
         'OK', 'Information') | Out-Null"
    );
    let _ = std::process::Command::new("powershell")
        .args(["-WindowStyle", "Hidden", "-NonInteractive", "-Command", &script])
        .creation_flags(CREATE_NO_WINDOW)
        .output();
}

// ---------------------------------------------------------------------------
// Installer download
// ---------------------------------------------------------------------------

fn installer_download_url(tag: &str) -> String {
    let version = tag.trim_start_matches('v');
    format!(
        "https://github.com/Bishi/auto-scraper-agent/releases/download/{tag}/\
         Auto-Scraper.Agent_{version}_x64-setup.exe"
    )
}

fn set_tray_tooltip(app: &AppHandle, msg: &str) {
    if let Some(tray) = app.tray_by_id("main") {
        // Toggling to a zero-width space before setting the real text forces
        // Windows to re-render the tooltip popup if it's currently displayed.
        let _ = tray.set_tooltip(Some("\u{200B}"));
        let _ = tray.set_tooltip(Some(msg));
    }
}

/// Stream the installer for `tag` to %TEMP%, updating the tray tooltip with
/// download progress.  Returns the path to the downloaded file.
///
/// Uses a GET (not HEAD) so redirects are followed before checking the status
/// and content-length — GitHub release assets redirect to a CDN and HEAD often
/// returns 0 for content-length on the redirect response.
///
/// Fails immediately with a clear error if the server returns a non-2xx status
/// (e.g. 404 when the CI hasn't finished uploading the asset yet), preventing
/// a GitHub HTML error page from being written to disk as a fake installer.
fn download_installer(tag: &str, app: &AppHandle) -> Result<PathBuf, String> {
    let version = tag.trim_start_matches('v');
    let url     = installer_download_url(tag);
    let dest    = std::env::temp_dir()
        .join(format!("auto-scraper-agent-{version}-setup.exe"));

    let client = reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(300)) // 5 min — large file
        .build()
        .map_err(|e| e.to_string())?;

    // Open the connection first so we can validate the status before touching disk.
    let mut response = client.get(&url).send().map_err(|e| e.to_string())?;

    // Fail fast — a non-success status means the release asset doesn't exist yet.
    // Without this check, a 404 HTML page gets saved as the installer and Windows
    // rejects it as an "Unsupported 16-bit Application".
    if !response.status().is_success() {
        return Err(format!(
            "HTTP {} — release asset not found for v{version}.\n\
             The installer may still be building. Try again in a few minutes,\n\
             or download manually from github.com/Bishi/auto-scraper-agent/releases.",
            response.status().as_u16()
        ));
    }

    // content_length() from the CDN response (after redirects) is reliable here.
    let total_bytes: u64 = response.content_length().unwrap_or(0);

    // Skip download if the file is already fully present (sizes must match).
    if total_bytes > 0 {
        if let Ok(meta) = std::fs::metadata(&dest) {
            if meta.len() == total_bytes {
                eprintln!("[agent] Installer already downloaded: {}", dest.display());
                return Ok(dest);
            }
        }
    }

    // Remove any stale / partial file from a previous failed attempt.
    let _ = std::fs::remove_file(&dest);

    eprintln!("[agent] Downloading installer from {url}");
    set_tray_tooltip(app, "Auto-Scraper — Starting download…");
    if let Ok(mut g) = DOWNLOAD_PROGRESS.lock() { *g = Some("Starting download…".into()); }

    let mut file = File::create(&dest).map_err(|e| e.to_string())?;
    let mut downloaded: u64 = 0;
    let mut buf = vec![0u8; 65_536]; // 64 KB chunks

    loop {
        let n = response.read(&mut buf).map_err(|e| e.to_string())?;
        if n == 0 { break; }
        file.write_all(&buf[..n]).map_err(|e| e.to_string())?;
        downloaded += n as u64;

        let progress = if total_bytes > 0 {
            format!(
                "{} / {} MB ({}%)",
                downloaded  / 1_048_576,
                total_bytes / 1_048_576,
                downloaded * 100 / total_bytes,
            )
        } else {
            format!("{} MB", downloaded / 1_048_576)
        };
        set_tray_tooltip(app, &format!("Auto-Scraper — Downloading update: {progress}"));
        if let Ok(mut g) = DOWNLOAD_PROGRESS.lock() { *g = Some(progress); }
    }

    if let Ok(mut g) = DOWNLOAD_PROGRESS.lock() { *g = None; }
    eprintln!("[agent] Download complete: {} bytes", downloaded);
    Ok(dest)
}


/// Launch the NSIS installer so its window is more likely to appear in the foreground on Windows.
/// Uses `cmd /c start` (ShellExecute) first; falls back to PowerShell `Start-Process -WindowStyle Normal`.
#[cfg(target_os = "windows")]
fn launch_installer_in_foreground(installer_path: &std::path::Path) -> std::io::Result<()> {
    let path_str = installer_path.as_os_str().to_string_lossy();
    let mut cmd = std::process::Command::new("cmd.exe");
    cmd.args(["/C", "start", "", path_str.as_ref()])
        .creation_flags(CREATE_NO_WINDOW);
    if cmd.spawn().is_ok() {
        return Ok(());
    }
    let escaped = installer_path.to_string_lossy().replace('\'', "''");
    std::process::Command::new("powershell")
        .args([
            "-WindowStyle",
            "Hidden",
            "-NonInteractive",
            "-Command",
            &format!("Start-Process -FilePath '{escaped}' -WindowStyle Normal"),
        ])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()?;
    Ok(())
}

#[cfg(not(target_os = "windows"))]
fn launch_installer_in_foreground(installer_path: &std::path::Path) -> std::io::Result<()> {
    std::process::Command::new(installer_path).spawn()?;
    Ok(())
}


// ---------------------------------------------------------------------------
// Full update flow: dialog → download → install dialog → launch → exit
// ---------------------------------------------------------------------------

/// Called whenever we know `latest_tag` is newer than the running version.
/// Guards against concurrent calls with UPDATE_IN_PROGRESS.
fn handle_update_available(app: &AppHandle, latest_tag: &str) {
    // Only one update flow at a time
    if UPDATE_IN_PROGRESS.swap(true, Ordering::SeqCst) {
        return;
    }

    let version = latest_tag.trim_start_matches('v');
    let current = app.package_info().version.to_string();

    let want_download = dialog_yes_no(
        "Update Available",
        &format!(
            "Auto-Scraper Agent v{version} is available  (you have v{current}).\n\n\
             Download and install now?  (~150 MB)\n\n\
             Progress will be shown in the tray tooltip."
        ),
    );

    if !want_download {
        UPDATE_IN_PROGRESS.store(false, Ordering::SeqCst);
        set_tray_tooltip(app, &format!("Auto-Scraper Agent — Update available: v{version}"));
        sidecar_log_quick("info", &format!("[agent] Update v{version} postponed by user"));
        return;
    }

    sidecar_log_quick("info", &format!("[agent] Downloading update v{version}…"));

    match download_installer(latest_tag, app) {
        Ok(installer_path) => {
            set_tray_tooltip(app, "Auto-Scraper Agent — Update ready");
            sidecar_log_quick("info", &format!("[agent] Update v{version} downloaded — prompting to install"));

            let want_install = dialog_yes_no(
                "Update Ready",
                &format!(
                    "v{version} has been downloaded.\n\n\
                     Install now?  The agent will restart automatically."
                ),
            );

            if want_install {
                sidecar_log_quick("info", &format!("[agent] Installing update v{version} — agent will restart"));
                eprintln!("[agent] Launching installer: {}", installer_path.display());
                // Hide the window before launching so Windows' focus-stealing prevention
                // doesn't block the installer from appearing in the foreground.
                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.hide();
                }
                if let Err(e) = launch_installer_in_foreground(&installer_path) {
                    eprintln!("[agent] Could not launch installer: {e}");
                    UPDATE_IN_PROGRESS.store(false, Ordering::SeqCst);
                    dialog_ok(
                        "Install Failed",
                        &format!(
                            "Could not start the installer.\n\nTry running manually:\n{}",
                            installer_path.display()
                        ),
                    );
                } else {
                    // Brief pause so Windows can foreground the new process before we exit.
                    thread::sleep(Duration::from_millis(600));
                    app.exit(0);
                }
            } else {
                // Keep the file for next time; reset the flag so the user can
                // trigger installation again from the tray menu.
                UPDATE_IN_PROGRESS.store(false, Ordering::SeqCst);
                set_tray_tooltip(app, "Auto-Scraper Agent — Update ready (not yet installed)");
                sidecar_log_quick("info", &format!("[agent] Update v{version} installation postponed by user"));
            }
        }
        Err(e) => {
            eprintln!("[agent] Download failed: {e}");
            sidecar_log_quick("error", &format!("[agent] Update download failed: {e}"));
            if let Ok(mut g) = DOWNLOAD_PROGRESS.lock() { *g = None; }
            UPDATE_IN_PROGRESS.store(false, Ordering::SeqCst);
            set_tray_tooltip(app, "Auto-Scraper Agent");
            dialog_ok("Download Failed", &format!("Could not download the update:\n\n{e}"));
        }
    }
}

fn sidecar_has_api_key() -> bool {
    reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()
        .ok()
        .and_then(|c| {
            c.get("http://127.0.0.1:9001/health")
                .send()
                .ok()
                .and_then(|r| r.json::<HealthResponse>().ok())
        })
        .map(|h| h.has_api_key)
        .unwrap_or(false)
}

fn sidecar_server_url() -> String {
    reqwest::blocking::Client::builder()
        .timeout(Duration::from_secs(2))
        .build()
        .ok()
        .and_then(|c| {
            with_token(c.get("http://127.0.0.1:9001/config"))
                .send()
                .ok()
                .and_then(|r| r.json::<serde_json::Value>().ok())
        })
        .and_then(|v| v["serverUrl"].as_str().map(String::from))
        .unwrap_or_else(|| "http://localhost:3000".to_string())
}

fn open_setup_window<R: Runtime>(app: &AppHandle<R>, tab: Option<&str>) {
    if let Some(win) = app.get_webview_window("setup") {
        // Window already exists — just bring it to front.
        let _ = win.show();
        let _ = win.set_focus();
        return;
    }
    let url_path = match tab {
        Some(t) => format!("index.html?tab={}", t),
        None    => "index.html".to_string(),
    };
    let _ = tauri::WebviewWindowBuilder::new(
        app,
        "setup",
        tauri::WebviewUrl::App(url_path.into()),
    )
    .title("Auto-Scraper Agent")
    .decorations(false)
    .background_color(Color(9, 17, 28, 255))
    .inner_size(860.0, 700.0)
    .min_inner_size(760.0, 620.0)
    .resizable(true)
    .center()
    .build();
}

// ---------------------------------------------------------------------------
// Tray menu
// ---------------------------------------------------------------------------

fn build_tray_menu<R: Runtime>(app: &AppHandle<R>) -> tauri::Result<Menu<R>> {
    let run_now       = MenuItem::with_id(app, "run_now",       "Run Now",             true, None::<&str>)?;
    let open          = MenuItem::with_id(app, "open",          "Open Dashboard",      true, None::<&str>)?;
    let setup         = MenuItem::with_id(app, "setup",         "Settings / Setup",    true, None::<&str>)?;
    let check_updates = MenuItem::with_id(app, "check_updates", "Check for Updates",   true, None::<&str>)?;
    let sep           = PredefinedMenuItem::separator(app)?;
    let quit          = MenuItem::with_id(app, "quit",          "Quit",                true, None::<&str>)?;
    Menu::with_items(app, &[&run_now, &open, &setup, &sep, &check_updates, &quit])
}

fn handle_menu_event(app: &AppHandle, event: MenuEvent) {
    match event.id().as_ref() {
        "run_now" => {
            // Fire the scrape in the background — don't block the menu event handler.
            let _ = reqwest::blocking::Client::builder()
                .timeout(Duration::from_secs(5))
                .build()
                .map(|c| with_token(c.post("http://127.0.0.1:9001/scrape/now")).send());
            // Open (or focus) the agent window on the Logs tab so the user can
            // see live progress without having to open it manually.
            open_setup_window(app, Some("logs"));
        }
        "open" => {
            let url = sidecar_server_url();
            let _ = app.opener().open_url(&url, None::<String>);
        }
        "setup" => {
            open_setup_window(app, None);
        }
        "check_updates" => {
            let app_clone = app.clone();
            let current_version = app.package_info().version.to_string();
            thread::spawn(move || {
                sidecar_log_quick("info", "[agent] Checking for updates…");
                match check_for_update(&current_version) {
                    Ok(Some(latest_tag)) => {
                        if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                            *guard = Some(latest_tag.clone());
                        }
                        handle_update_available(&app_clone, &latest_tag);
                    }
                    Ok(None) => {
                        eprintln!("[agent] App is up to date");
                        sidecar_log_quick("info", "[agent] Update check: already on latest version");
                        if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                            *guard = None;
                        }
                        dialog_ok(
                            "Up to Date",
                            &format!("Auto-Scraper Agent v{current_version} is the latest version."),
                        );
                    }
                    Err(e) => {
                        sidecar_log_quick("error", &format!("[agent] Update check failed: {e}"));
                        dialog_ok("Update Check Failed", &format!("Could not reach the update server.\n\n{e}"));
                    }
                }
            });
        }
        "quit" => {
            let _ = with_token(reqwest::blocking::Client::new().post("http://127.0.0.1:9001/stop"))
                .send();
            thread::sleep(Duration::from_millis(600));
            app.exit(0);
        }
        _ => {}
    }
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            Some(vec![]),
        ))
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_shell::init())
        .invoke_handler(tauri::generate_handler![
            save_config,
            get_update_version,
            install_update,
            get_sidecar_token,
            is_update_check_done,
            get_update_check_error,
            get_download_progress,
            window_minimize,
            window_toggle_maximize,
            window_close,
            window_start_dragging
        ])
        .setup(|app| {
            // Clean up any leftover installer files from a previous auto-update.
            // Done in a background thread with a delay: NSIS may still be alive
            // (showing the Finish page) when the new agent starts, keeping the
            // file locked. 30 s is enough for the user to click Finish.
            thread::spawn(|| {
                thread::sleep(Duration::from_secs(30));
                let temp = std::env::temp_dir();
                if let Ok(entries) = std::fs::read_dir(&temp) {
                    for entry in entries.flatten() {
                        let name = entry.file_name();
                        let name = name.to_string_lossy();
                        if name.starts_with("auto-scraper-agent-") && name.ends_with("-setup.exe") {
                            if std::fs::remove_file(entry.path()).is_ok() {
                                eprintln!("[agent] Cleaned up old installer: {}", entry.path().display());
                            }
                        }
                    }
                }
            });

            // Spawn the Node.js sidecar.
            let sidecar_cmd = app
                .shell()
                .sidecar("scraper-node")
                .expect("scraper-node sidecar not configured");

            let (rx, child) = sidecar_cmd
                .spawn()
                .expect("failed to spawn scraper-node sidecar");

            // Prevent any kill-on-drop behaviour. The sidecar must live for
            // the entire app lifetime; the "Quit" menu item shuts it down via
            // POST /stop before calling app.exit(0).
            std::mem::forget(child);

            // Watchdog: drain the event channel (keeps the OS pipe flowing so
            // sidecar stdout never blocks) and restart the sidecar automatically
            // if it crashes. On each restart the sidecar re-reads its saved
            // config from disk, so the scheduler resumes without user action.
            let watchdog_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                let mut rx = rx;
                loop {
                    let mut token_captured = false;
                    // Drain events until the sidecar exits.
                    while let Some(event) = rx.recv().await {
                        match event {
                            CommandEvent::Stdout(bytes) if !token_captured => {
                                // Parse SIDECAR_TOKEN=<hex> from the first stdout line.
                                // Written by the sidecar via process.stdout.write before
                                // the HTTP server starts, so it always arrives first.
                                let text = String::from_utf8_lossy(&bytes);
                                for line in text.lines() {
                                    if let Some(token) = line.strip_prefix("SIDECAR_TOKEN=") {
                                        let token = token.trim().to_string();
                                        if !token.is_empty() {
                                            if let Ok(mut guard) = SIDECAR_TOKEN.lock() {
                                                *guard = Some(token);
                                            }
                                            token_captured = true;
                                            break;
                                        }
                                    }
                                }
                            }
                            CommandEvent::Terminated(payload) => {
                                eprintln!(
                                    "[agent] Sidecar exited (code {:?}), restarting in 3 s…",
                                    payload.code
                                );
                                // Invalidate the old token so stale callers get 401
                                // rather than silently using a dead secret.
                                if let Ok(mut guard) = SIDECAR_TOKEN.lock() {
                                    *guard = None;
                                }
                                break;
                            }
                            _ => {}
                        }
                    }
                    // Brief pause to avoid a tight crash loop.
                    tauri::async_runtime::spawn_blocking(|| {
                        std::thread::sleep(std::time::Duration::from_secs(3));
                    })
                    .await
                    .ok();
                    // Re-spawn the sidecar.
                    match watchdog_handle
                        .shell()
                        .sidecar("scraper-node")
                        .and_then(|c| c.spawn())
                    {
                        Ok((new_rx, new_child)) => {
                            std::mem::forget(new_child);
                            rx = new_rx;
                            eprintln!("[agent] Sidecar restarted.");
                        }
                        Err(e) => {
                            eprintln!("[agent] Could not restart sidecar: {e}");
                            break;
                        }
                    }
                }
            });

            // Build tray icon — created entirely in Rust so there is only one icon.
            // (No trayIcon section in tauri.conf.json.)
            let menu = build_tray_menu(app.handle())?;
            let app_handle_tray = app.handle().clone();

            let mut tray = TrayIconBuilder::with_id("main")
                .menu(&menu)
                .menu_on_left_click(false)
                .tooltip("Auto-Scraper Agent");
            if let Some(icon) = app.default_window_icon() {
                tray = tray.icon(icon.clone());
            }
            tray.on_menu_event(move |app, event| handle_menu_event(app, event))
                .on_tray_icon_event(move |_tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        // Left-click always opens/focuses the window. When no API
                        // key is saved yet, open on Settings; otherwise open on Logs.
                        let tab = if sidecar_has_api_key() { Some("logs") } else { None };
                        open_setup_window(&app_handle_tray, tab);
                    }
                })
                .build(app)?;

            // Wait for sidecar in background, then open the window.
            // Not configured yet → Settings tab so the user can enter credentials.
            // Already configured  → Logs tab so they can see activity straight away.
            let handle = app.handle().clone();
            thread::spawn(move || {
                if wait_for_sidecar() {
                    let tab = if sidecar_has_api_key() { Some("logs") } else { None };
                    open_setup_window(&handle, tab);
                } else {
                    eprintln!("[agent] Sidecar did not start within 10 seconds");
                }
            });

            // Background thread: silently check for updates on startup (after 15 s delay)
            // then every 6 h (GitHub API - keep interval conservative).
            // Stores the latest tag in AVAILABLE_UPDATE so the renderer
            // can show a non-intrusive badge. No dialog is shown automatically.
            let current_version = app.package_info().version.to_string();
            thread::spawn(move || {
                let log_client = reqwest::blocking::Client::builder()
                    .timeout(Duration::from_secs(3))
                    .build()
                    .ok();
                thread::sleep(Duration::from_secs(15));
                loop {
                    match check_for_update(&current_version) {
                        Ok(Some(latest_tag)) => {
                            eprintln!("[agent] Update available: {}", latest_tag);
                            if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                                *guard = Some(latest_tag.clone());
                            }
                            if let Some(ref c) = log_client {
                                sidecar_log(c, "info", &format!("[agent] Update available: {} — click the badge to install", latest_tag));
                            }
                        }
                        Ok(None) => {
                            if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                                *guard = None; // clear stale entry if somehow rolled back
                            }
                        }
                        Err(e) => {
                            // Background check — log silently, don't show a dialog
                            eprintln!("[agent] Background update check failed: {e}");
                        }
                    }
                    thread::sleep(Duration::from_secs(6 * 60 * 60));
                }
            });

            // Background thread: poll /schedule every 30 s and update the tray tooltip
            // so the user can see the next scrape time by hovering the tray icon.
            let tooltip_handle = app.handle().clone();
            thread::spawn(move || {
                let client = match reqwest::blocking::Client::builder()
                    .timeout(Duration::from_secs(2))
                    .build()
                {
                    Ok(c) => c,
                    Err(_) => return,
                };
                loop {
                    thread::sleep(Duration::from_secs(30));

                    // Check if the server sent a check_update command to this agent.
                    let update_pending = with_token(client.get("http://127.0.0.1:9001/update/check"))
                        .send()
                        .ok()
                        .and_then(|r| r.json::<UpdateCheckResponse>().ok())
                        .map(|r| r.pending)
                        .unwrap_or(false);
                    if update_pending {
                        // Remote check_update from admin — silent: just set the badge,
                        // do NOT show a dialog. User sees the amber pill and updates
                        // when ready. Only tray "Check for Updates" / badge click shows a dialog.
                        let current_version = tooltip_handle.package_info().version.to_string();
                        match check_for_update(&current_version) {
                            Ok(Some(latest_tag)) => {
                                if let Ok(mut guard) = AVAILABLE_UPDATE.lock() {
                                    *guard = Some(latest_tag.clone());
                                }
                                sidecar_log(&client, "info", &format!("[agent] Update available: {} — click the badge to install", latest_tag));
                            }
                            Ok(None) => {
                                sidecar_log(&client, "info", "[agent] Update check: already on latest version");
                            }
                            Err(e) => {
                                sidecar_log(&client, "error", &format!("[agent] Update check failed: {e}"));
                            }
                        }
                    }

                    let tooltip = with_token(client.get("http://127.0.0.1:9001/schedule"))
                        .send()
                        .ok()
                        .and_then(|r| r.json::<ScheduleResponse>().ok())
                        .map(|s| {
                            if let Some(next_ms) = s.next_run_at {
                                let now_ms = std::time::SystemTime::now()
                                    .duration_since(std::time::SystemTime::UNIX_EPOCH)
                                    .map(|d| d.as_millis() as u64)
                                    .unwrap_or(0);
                                let diff_min = next_ms.saturating_sub(now_ms) / 60_000;
                                format!("Auto-Scraper — next scrape in {} min", diff_min)
                            } else {
                                "Auto-Scraper — scraping now…".to_string()
                            }
                        })
                        .unwrap_or_else(|| "Auto-Scraper Agent".to_string());
                    if let Some(tray) = tooltip_handle.tray_by_id("main") {
                        let _ = tray.set_tooltip(Some(tooltip.as_str()));
                    }
                }
            });

            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app, event| {
            // Keep the process alive when all windows are closed so the tray
            // icon persists.
            // IMPORTANT: only prevent exit when triggered by a window close
            // (code is None). When the "Quit" menu item calls app.exit(0),
            // code is Some(0) — do NOT prevent it or Quit silently does nothing.
            if let tauri::RunEvent::ExitRequested { api, code, .. } = event {
                if code.is_none() {
                    api.prevent_exit();
                }
            }
        });
}
